// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLoFDg8STP_1P54Dan8bZCivg_iXYl8mA',
    appId: '1:842460120454:web:32832a4c3a0da681201807',
    messagingSenderId: '842460120454',
    projectId: 'budget-life-e1036',
    authDomain: 'budget-life-e1036.firebaseapp.com',
    storageBucket: 'budget-life-e1036.appspot.com',
    measurementId: 'G-SDLK702P72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4j8SzGZScsuIyXU87ssSDbgss3f8CEpA',
    appId: '1:842460120454:android:2d44442ed05ea496201807',
    messagingSenderId: '842460120454',
    projectId: 'budget-life-e1036',
    storageBucket: 'budget-life-e1036.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9Us4GEnHMv-5QxCZZfQ9Azpc3rkB-d2A',
    appId: '1:842460120454:ios:a95542e76ec6eb7e201807',
    messagingSenderId: '842460120454',
    projectId: 'budget-life-e1036',
    storageBucket: 'budget-life-e1036.appspot.com',
    iosClientId: '842460120454-fmts7316lige5kcamfhtjkm6qpqfgl03.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgeta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9Us4GEnHMv-5QxCZZfQ9Azpc3rkB-d2A',
    appId: '1:842460120454:ios:9543bb196910def8201807',
    messagingSenderId: '842460120454',
    projectId: 'budget-life-e1036',
    storageBucket: 'budget-life-e1036.appspot.com',
    iosClientId: '842460120454-r5ltdqmejkm5dhn634gph42oha6em4vr.apps.googleusercontent.com',
    iosBundleId: 'com.example.budget',
  );
}
